# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Phind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Phind
  pod 'RealmSwift'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'TransitionableTab', '~> 0.2.0'
  pod 'JustLog'
  pod 'garland-view'

  target 'PhindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhindUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
